Repository NiceKingdom/Demo, pull requests merged in 2019-01, with the labels that each got.

#12 Population change
  frontend/build/utils.js
  frontend/src/assets/scss/global_css.scss
  frontend/src/assets/scss/mycss_lib.scss
  frontend/src/components/building.vue
  frontend/src/components/hello.vue
  frontend/src/components/manor.vue
  frontend/src/components/plat.vue
  frontend/src/components/register.vue
  frontend/src/components/sub/building-list.vue
  frontend/src/components/sub/progress.vue
  frontend/src/store/index.js
Labels: bug, enhancement

#13 增加两种政策
  README.md
  app/Http/Controllers/Common/ResourceController.php
  app/Policy.php
  app/UserHistory.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2019_01_06_165653_create_user_histories_table.php
  database/migrations/2019_01_06_174250_create_policies_table.php
  database/seeds/UsersTableSeeder.php
  frontend/src/components/sub/progress.vue
  routes/web.php
  tests/Feature/BuildingTest.php
  tests/Feature/ResourcePolicyTest.php
  tests/Feature/UserTest.php
  tests/Unit/ExampleTest.php
Labels: bug, feature

#14 增加获取政策历史
  app/Http/Controllers/Common/ResourceController.php
  routes/web.php
Labels: bug, feature

#15 修改building页面button标签的样式
  frontend/src/components/building.vue
Labels: bug, enhancement

#16 发送空气质量提醒邮件到给定的用户
  app/Http/Controllers/Common/UserController.php
  app/Mail/AirQualityWarning.php
  app/Models/Log.php
  app/Policy.php
  composer.json
  composer.lock
  resources/views/emails/other/airQuality.blade.php
Labels: feature

#18 增加政策检查器并修正资源自增
  app/Http/Controllers/Common/InitializeController.php
  app/Http/Controllers/Common/ResourceController.php
  app/Http/Controllers/Common/UserController.php
  app/Http/Kernel.php
  app/Http/Middleware/AutoCheck.php
  app/Http/Middleware/BuildingCheck.php
  app/Http/Middleware/ResourceAuto.php
  app/Policy.php
  app/Service/BuildingService.php
  app/helpers.php
  routes/web.php
  tests/Feature/ResourcePolicyTest.php
Labels: bug, enhancement

#19 修复食物与人口的增长关系
  0Doc/people-food-auto.htm
  app/Http/Middleware/ResourceAuto.php
  database/migrations/2018_05_24_172310_create_resources_table.php
  database/migrations/2018_05_25_231700_create_buildings_table.php
  public/css/app.0d4dfaf4ee6c22c072f20e3333cab5ae.css
  public/css/app.0d4dfaf4ee6c22c072f20e3333cab5ae.css.map
  public/js/app.d37a737efab08ab4426f.js
  public/js/app.d37a737efab08ab4426f.js.map
  public/js/manifest.1766e3c7586055624ca0.js
  public/js/manifest.1766e3c7586055624ca0.js.map
  public/js/vendor.eb734cc7e310ccee09d6.js
  public/js/vendor.eb734cc7e310ccee09d6.js.map
Labels: bug

#20 增加 `npm build` 的自动编译及上线脚本
  .gitignore
  README.md
  frontend/config/index.js.bac
  sh
Labels: enhancement

#22 修复“Demo测试情况“中的bug
  frontend/src/components/building.vue
  frontend/src/components/sub/resource-bar.vue
  frontend/src/store/index.js
Labels: bug

#23 解决 BUG 并增加一些闲置的新字段
  app/Console/Kernel.php
  app/Http/Controllers/Common/InitializeController.php
  app/Http/Controllers/Common/ResourceController.php
  app/Http/Controllers/Common/UserController.php
  app/Policy.php
  app/Service/BuildingService.php
  database/migrations/2018_05_25_231700_create_buildings_table.php
Labels: bug
